#!/usr/bin/env node

import { Command } from 'commander';
import {
  setEnv,
  deployCDK,
  destroyCDK,
  copyEnv,
  ssh,
  checkIPandPemPath,
  setupEc2,
  allSteps,
} from './cli_util.js';

const program = new Command();

program
  .name('paisley')
  .description('Paisley CLI tool to manage environment variables and interact with Paisley on your AWS.')

program
  .command('start')
  .description('For first time use, executes the following steps in sequence: "env", "deploy", "copy-env", "initiate"')
  .action(allSteps)

// program
//   .name('pause')
//   .description('Pause for 30s to allow background processing to occur')
//   .action(pause)

program
  .command('env')
  .description('Change environment variables and API keys within the .env')
  .action(setEnv)

program
  .command('deploy')
  .description('Synthesizes, and deploys Paisley on AWS using AWS CDK')
  .action(deployCDK)

program
  .command('copy-env')
  .description('Updates environment variables within .env after deploying to AWS')
  .action(copyEnv)

program
  .command('initiate')
  .description('Executes final DB, UI, and Paisley server intiation')
  .action(setupEc2)

program
  .command('ssh')
  .description('SSH into the deployed EC2 instance')
  .action(ssh)

program
  .command('check-env')
  .description('Check PUBLIC_IP of deployed Paisley instance from .env')
  .action(checkIPandPemPath)

program
  .command('destroy')
  .description('Tear down deployed Paisley AWS infrastructure')
  .action(destroyCDK)

program.parse(process.argv);